#############################################################################################
# This file is based on https://github.com/EmbarkStudios/cargo-fetcher/blob/master/deny.toml
#############################################################################################

targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "x86_64-unknown-linux-musl" },
    { triple = "x86_64-apple-darwin" },
    { triple = "x86_64-pc-windows-msvc" },
]

[advisories]
vulnerability = "deny"
unmaintained = "deny"
notice = "deny"
ignore = [
]

[bans]
multiple-versions = "deny"
deny = [
    # we never want a dependency on openssl due to all of the cross platform
    # issues it has, particularly on windows
    { name = "openssl" },
    { name = "openssl-sys" },
]
skip = [
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-git = []

[licenses]
unlicensed = "deny"
allow-osi-fsf-free = "neither"
copyleft = "deny"
confidence-threshold = 0.92
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "MIT",
    "MPL-2.0",
    "Zlib",
]

[[licenses.clarify]]
name = "ring"
# SPDX considers OpenSSL to encompass both the OpenSSL and SSLeay licenses
# https://spdx.org/licenses/OpenSSL.html
# ISC - Both BoringSSL and ring use this for their new files
# MIT - "Files in third_party/ have their own licenses, as described therein. The MIT
# license, for third_party/fiat, which, unlike other third_party directories, is
# compiled into non-test libraries, is included below."
# OpenSSL - Obviously
expression = "ISC AND MIT AND OpenSSL"
license-files = [ ]

[[licenses.clarify]]
name = "webpki"
expression = "ISC"
license-files = [ ]